var core = require('./core');
var db = require('./db');
var fs = require('fs');
var configuration = require("./configuration");
var extensions = core.extensions.load(process.cwd()+"/"+configuration.extensionsPath);
var ext_utils = require('./extension_utils.js');

var extensionIri = process.argv[2];
if(extensionIri == null) {
    console.log("(!!!) The IRI of the extension must be provided as the script first argument");
    process.exit(1);
};

var ExtensionModule = core.extensions.findExtension(extensionIri, extensions);

if(ExtensionModule == null) {
    console.log("(!!!) Impossible to load extension "+extensionIri);
    process.exit(1);
};


var accountIri = process.argv[3];
if(accountIri == null) {
    console.log("(!!!) The IRI of an account generated by this extension must be provided as the script second argument");
    process.exit(1);
}

var command = process.argv[4];
if(command == null) {
    console.log("(!!!) A command [execute|import] must be provided as the script third argument");
    process.exit(1);
}


var handleDefaultMessages = function(msg) {
    switch(msg.msg) {
    case 'stop' : 
        process.exit(0);
    default:
        return false;
    }
};

var dbClient = new db.DB();

dbClient.findRDFNode('accounts', accountIri, function(err, account){
    if(!err && account!=null) {
        dbClient.findAll('bindings', {"srcfg:account_generated_by" : ExtensionModule.iri}, function(err, bindings) {
            if(!err && bindings!=null) {
                var extension = new ExtensionModule();
                process.on('message', function(msg){
                    if(!handleDefaultMessages(msg)) {
                        extension.handleMessage(msg);
                    }
                });
                if(command == 'execute') {
                    extension.execute(account,bindings,dbClient); 
                } else if(command == 'import') {
                    extension.import(account,bindings,dbClient);
                } else {
                    ext_utils.send_error("Unknown command "+command);
                }
            } else {
                ext_utils.send_error("Cannot find bindings");
            }
        });
    } else {
        ext_utils.send_error("Cannot find account");
        process.exit(1);
    }
});
